rvm:
  - 1.9.3
  - 2.0.0
notifications:
  recipients:
    - jari.bakken@gmail.com
    - p0deje@gmail.com
    - jarmo.p@gmail.com
  irc: "irc.freenode.net#watir"
before_script:
  - support/travis.sh
env:
  - WATIR_WEBDRIVER_BROWSER=chrome
matrix:
  allow_failures:
    - env: WATIR_WEBDRIVER_BROWSER=phantomjs
    - env: WATIR_WEBDRIVER_BROWSER=phantomjs ALWAYS_LOCATE=false
    - env: WATIR_WEBDRIVER_BROWSER=phantomjs PREFER_CSS=1 SELECTOR_STATS=1
